#!/bin/bash
#
set -e

export PATH=$PATH:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:.
. <( arv-dax setup )

mnt=`arv-dax keep`
jobparam=`arv-dax script_parameters`

clinvar=$mnt/`echo "$jobparam" | jq -r .CLINVAR`
vcf=$mnt/`echo "$jobparam" | jq -r .VCF`

bn_clinvar=`basename "$clinvar"`
if [ "$bn_clinvar" != "clinvar.vcf" ]
then
  clinvar="$clinvar"/clinvar.vcf
fi

vcfdir="$vcf"
bn_vcf=`basename "$vcf"`

echo ">>>>> bn_vcf $bn_vc"

if [[ "$bn_vcf" =~ \.vcf$ ]]
then
  vcfdir=`dirname "$vcf"`

  echo ">>>> calling dirname on vcf file ($vcf -> $vcfdir)"
fi

echo ">>>>>> starting with clinvar $clinvar vcfdir $vcfdir"

#!/bin/bash
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for input_vcf in `ls "$vcfdir"`
do
  echo ">>>>>>>>> processing $vcfdir/$input_vcf (using $clinvar).  creating ${b}_clinvar_report.csv"
  b=`basename "$input_vcf" .vcf`
  clinvar-report.py -C "$clinvar" -i "$vcfdir/$input_vcf" -F csv > "$b"_clinvar_report.csv
done
IFS=$SAVEIFS

arv-dax task finish
exit 0
